mongodb:
  extends:
    file: common.yml
    service: mongodb
  ports:
    - "27017:27017"

redis:
  extends:
    file: common.yml
    service: redis

elastic:
  extends:
    file: common.yml
    service: elastic

postfix:
  extends:
    file: common.yml
    service: postfix

superdesk:
  net: "host"
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
   - postfix
  ports:
   - "443:443"
   - "80:80"
  environment:
   - SUPERDESK_URL=http://ec2-18-220-2-159.us-east-2.compute.amazonaws.com/api
   - SUPERDESK_WS_URL=ws://ec2-18-220-2-159.us-east-2.compute.amazonaws.com/ws
   - SUPERDESK_CLIENT_URL=http://ec2-18-220-2-159.us-east-2.compute.amazonaws.com
