mongodb:
  extends:
    file: common.yml
    service: mongodb
  ports:
    - "27017:27017"

redis:
  extends:
    file: common.yml
    service: redis

elastic:
  extends:
    file: common.yml
    service: elastic
  ports:
    - "9200:9200"

postfix:
  extends:
    file: common.yml
    service: postfix

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
   - postfix
  environment:
   - SUPERDESK_RELOAD=True
   - SUPERDESK_URL=http://ec2-18-220-2-159.us-east-2.compute.amazonaws.com:5000/api
   - SUPERDESK_WS_URL=ws://ec2-18-220-2-159.us-east-2.compute.amazonaws.com:5050
   - SUPERDESK_CLIENT_URL=http://ec2-18-220-2-159.us-east-2.compute.amazonaws.com:9000
  ports:
   - "5000:5000"
   - "5100:5100"
   - "5400:5400"
   - "35729:35729"
   - "9000:9000"
   - "80:80"
  volumes:
   - ../server:/opt/superdesk/
   - ../client:/opt/superdesk/client/
   - ../client-core:/opt/superdesk/client-core/
   - ./Procfile-dev:/opt/superdesk/Procfile
   - ./start-dev.sh:/opt/superdesk/start.sh
